version: "3.6"
services:
  besu:
    image: hyperledger/besu:${BESU_IMAGE_VERSION:-latest}
    ports:
      # mapping <Host Port>:<Container Port>
      - 8545:8545
      - 30303:30303
      - 9545:9545
    env_file:
      - ./.env
    environment:
      - BESU_ENV=${BESU_ENV:? "BESU_ENV is not set"}
    volumes:
      - type: bind
        source: ./config/besu/${BESU_ENV}
        target: /config
      - type: bind
        source: ./config/keys/${BESU_ENV}/rpcnode
        target: /opt/besu/keys
      - type: bind
        source: ./database/besu/${BESU_ENV}/
        target: /opt/besu/database
    entrypoint:
      - /bin/bash
      - -c
      - |
        # Log Besu version and help
        echo "Starting Besu node... BESU_ENV=${BESU_ENV}"
        echo "Besu version::>>" && besu --version
        echo "Besu --help :>>" && besu --help
        besu validate-config --config-file=/config/config.toml
        # Start Besu node with specified options
        besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM \
        ${BESU_OPTS}
    # To override a configuration
    # BESU_OPTS="--node-private-key-file=keys/key --rpc-http-enabled=false --rpc-http-port=8546" docker-compose up
