# your can use the init-foundry task to create a foundry.toml file.
# The file will be created using the proper values to make Foundry work well with your Hardhat project.
# See more config options https://github.com/gakonst/foundry/tree/master/config

[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test/foundry'
remappings = [
    'forge-std=lib/forge-std/src/',
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[fuzz]
runs = 1000

[rpc_endpoints]
# This section lives outside of profiles and defines a table of RPC endpoints, where the key specifies the RPC endpoints's name and the value is the RPC endpoint itself.
# The value can either be a valid RPC endpoint or a reference to an environment variable (wrapped with in ${}).
# These RPC endpoints can be used in tests and Solidity scripts 
mainnet = "${RPC_URL}"

# to run tests with deep_test profile type: export FOUNDRY_PROFILE=deep_test
[profile.deep_test.fuzz]
runs = 5000

# [profile.ci.fuzz]
# runs = 5000
# seed = 0x00
