name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Check contracts are linted
        run: yarn lint:check

      - name: Add lint summary
        run: |
          echo '## Lint results' >> $GITHUB_STEP_SUMMARY
          echo '✅ Passed' >> $GITHUB_STEP_SUMMARY

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install node
        uses: actions/setup-node@v3

      - name: Install yarn
        run: npm i -g yarn

      - name: Clone repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: yarn install

      - name: Show Foundry config
        run: forge config --config-path=./contracts/foundry.toml

      - name: Run forge and hardhat tests
        run: yarn test:sol

      - name: Run typescript tests
        run: yarn test:ts

      - name: Add test summary
        run: |
          echo '## Test results' >> $GITHUB_STEP_SUMMARY
          echo '✅ Passed' >> $GITHUB_STEP_SUMMARY

  coverage:
    name: Run Coverage Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Clone repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: yarn coverage:sol --report=summary --silent > ./summary.md
      - name: Add coverage summary
        run: |
          echo '## Coverage results' >> $GITHUB_STEP_SUMMARY
          echo "$(cat ./summary.md)" >> $GITHUB_STEP_SUMMARY

      - name: Coverage
        run: |
          # This generates contracts/lcov.info
          yarn coverage:sol --report=lcov --silent
      - name: Move lcov.info
        run: mv contracts/lcov.info lcov.info
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info

  full-pass:
    needs:
      - 'tests'
      - 'lint'

    runs-on: ubuntu-latest

    steps:
      - name: Add summary
        run: |
          echo '## Summary' >> $GITHUB_STEP_SUMMARY
          echo '✅ All passed' >> $GITHUB_STEP_SUMMARY
